import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { api } from '../services/api'

const categoryNames = { BOOK:'Livros', NOTEBOOK:'Cadernos', BACKPACK:'Mochilas', PENCIL:'Lápis', PEN:'Canetas', ERASER:'Borrachas', PENCIL_CASE:'Estojos', UNIFORM:'Uniformes', SHOES:'Calçados', SCHOOL_SUPPLIES:'Outros materiais' }
const conditionNames = { NEW:'Novo', GOOD:'Bom estado', FAIR:'Estado regular' }
const statusNames = { PENDING:'Pendente', APPROVED:'Aprovado', COMPLETED:'Concluído', CANCELED:'Cancelado' }
const categoryIcons = { BOOK:'📚', NOTEBOOK:'📓', BACKPACK:'🎒', PENCIL:'✏️', PEN:'🖊️', ERASER:'▰', PENCIL_CASE:'🧰', UNIFORM:'👕', SHOES:'👟', SCHOOL_SUPPLIES:'📐' }
const adminPaths = { users:'/users', items:'/items', orders:'/orders' }

function Notice({ error, success }) { return (error || success) ? <div className={`notice ${error ? 'error' : 'success'}`} role="alert">{error || success}</div> : null }
function Empty({ title, text, action }) { return <div className="empty"><span>♡</span><h3>{title}</h3><p>{text}</p>{action}</div> }
function ItemCard({ item }) { return <article className="item-card"><div className="item-visual"><span>{categoryIcons[item.category]}</span><em>{conditionNames[item.condition]}</em></div><div className="item-content"><small>{categoryNames[item.category]}</small><h3>{item.name}</h3><p>{item.description || 'Material disponível para uma nova história.'}</p><div><span>Por {item.user?.name || 'Doador(a)'}</span><Link to={`/catalogo/${item.id}`}>Ver detalhes →</Link></div></div></article> }
function PageHeading({ eyebrow, title, text, action }) { return <header className="page-heading"><div><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{action}</header> }

export function Home() {
  const [items, setItems] = useState([])
  useEffect(() => { api('/items?availability=AVAILABLE').then(data => setItems(data.slice(0,3))).catch(() => {}) }, [])
  return <>
    <section className="hero-section"><div className="hero-copy"><span className="eyebrow">Educação que circula, futuro que cresce</span><h1>O que você não usa mais pode <em>transformar</em> uma história.</h1><p>Conectamos quem tem materiais escolares em bom estado a estudantes que precisam deles. Simples, gratuito e perto de você.</p><div className="button-row"><Link className="button" to="/catalogo">Encontrar materiais</Link><Link className="button secondary" to="/doacoes/nova">Quero doar</Link></div><div className="trust"><span>✓ Gratuito</span><span>✓ Seguro</span><span>✓ Impacto local</span></div></div><div className="hero-art" aria-label="Ilustração de materiais escolares"><div className="sun"></div><span className="backpack">🎒</span><span className="book">📚</span><span className="pencil">✏️</span><div className="impact-card"><b>+ educação</b><small>- desperdício</small></div></div></section>
    <section className="steps-section"><header><small>É simples participar</small><h2>Um gesto em três passos</h2><p>A plataforma aproxima pessoas e torna cada doação clara e acompanhável.</p></header><div className="steps"><article><b>01</b><span>📦</span><h3>Cadastre</h3><p>Conte o que você deseja doar e informe o estado do material.</p></article><article><b>02</b><span>🤝</span><h3>Conecte</h3><p>Um estudante solicita o item e você acompanha o pedido.</p></article><article><b>03</b><span>🌱</span><h3>Transforme</h3><p>Combine a entrega e dê ao material uma nova oportunidade.</p></article></div></section>
    <section className="featured"><PageHeading eyebrow="Doações recentes" title="Materiais esperando uma nova história" text="Confira itens disponíveis agora na comunidade." action={<Link to="/catalogo">Ver todo o catálogo →</Link>}/><div className="item-grid">{items.map(item => <ItemCard item={item} key={item.id}/>)}</div></section>
    <section className="impact"><div><small>Impacto que vai além do material</small><h2>Quando um caderno circula, oportunidades também circulam.</h2><p>Ao reutilizar materiais escolares, reduzimos desperdício, apoiamos famílias e fortalecemos redes solidárias locais.</p><Link className="button light" to="/sobre">Conheça nossa missão</Link></div><div className="impact-numbers"><article><b>100%</b><span>gratuito para participar</span></article><article><b>1 item</b><span>pode mudar um semestre</span></article><article><b>∞</b><span>possibilidades de impacto</span></article></div></section>
  </>
}

export function Catalog() {
  const [items,setItems]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState(''); const [search,setSearch]=useState(''), [category,setCategory]=useState('')
  useEffect(()=>{ const params=new URLSearchParams({availability:'AVAILABLE'}); if(search)params.set('search',search); if(category)params.set('category',category); api(`/items?${params}`).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false)) },[search,category])
  return <div className="page"><PageHeading eyebrow="Catálogo solidário" title="Encontre o material que você precisa" text="Doações disponíveis, cadastradas por pessoas da comunidade."/><div className="filters"><label><span>Buscar</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex.: mochila, caderno..."/></label><label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{Object.entries(categoryNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label></div><Notice error={error}/>{loading?<div className="page-status">Carregando materiais...</div>:items.length?<div className="item-grid">{items.map(i=><ItemCard item={i} key={i.id}/>)}</div>:<Empty title="Nenhum material encontrado" text="Tente ajustar sua busca ou volte em breve."/>}</div>
}

export function ItemDetails() {
  const {id}=useParams(), {user}=useAuth(), navigate=useNavigate(); const [item,setItem]=useState(),[error,setError]=useState(''),[success,setSuccess]=useState('')
  useEffect(()=>{api(`/items/${id}`).then(setItem).catch(e=>setError(e.message))},[id])
  const request=async()=>{if(!user)return navigate('/login');try{await api('/orders',{method:'POST',body:JSON.stringify({itemId:id})});setSuccess('Solicitação enviada! Acompanhe o andamento em Pedidos.')}catch(e){setError(e.message)}}
  if(!item)return <div className="page"><Notice error={error}/><div className="page-status">Carregando...</div></div>
  return <div className="page"><Link className="back" to="/catalogo">← Voltar ao catálogo</Link><div className="detail"><div className="detail-visual"><span>{categoryIcons[item.category]}</span></div><div><small>{categoryNames[item.category]}</small><h1>{item.name}</h1><div className="tags"><span>{conditionNames[item.condition]}</span><span>Disponível</span></div><p>{item.description}</p><dl><div><dt>Doador(a)</dt><dd>{item.user?.name}</dd></div><div><dt>Como funciona</dt><dd>Envie a solicitação e aguarde o contato do doador.</dd></div></dl><Notice error={error} success={success}/>{item.userId===user?.id?<Link className="button secondary" to="/doacoes">Gerenciar minha doação</Link>:<button className="button" onClick={request}>Solicitar este material</button>}</div></div></div>
}

function AuthForm({register=false}) { const auth=useAuth(),navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:'',type:'RECEIVER',phones:[''],address:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false); const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{if(register)await auth.register(form);else await auth.login(form);navigate('/catalogo')}catch(err){setError(err.message)}finally{setBusy(false)}}; return <div className="auth-page"><div className="auth-panel"><Link className="brand" to="/"><img src="/logo.png" alt=""/><span>Passa <b>Adiante</b></span></Link><small>{register?'Faça parte da rede':'Que bom ter você de volta'}</small><h1>{register?'Crie sua conta':'Entre na sua conta'}</h1><p>{register?'Leva menos de dois minutos.':'Continue fazendo materiais e oportunidades circularem.'}</p><form onSubmit={submit}>{register&&<label>Nome completo<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>E-mail<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Senha<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{register&&<><label>Quero participar como<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="RECEIVER">Pessoa que busca materiais</option><option value="DONOR">Pessoa doadora</option><option value="INSTITUTION">Instituição</option></select></label><label>Telefone<input value={form.phones[0]} onChange={e=>setForm({...form,phones:[e.target.value]})}/></label><label>Município / endereço<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></>}<Notice error={error}/><button className="button wide" disabled={busy}>{busy?'Aguarde...':register?'Criar conta':'Entrar'}</button></form><p className="auth-switch">{register?'Já tem uma conta?':'Ainda não participa?'} <Link to={register?'/login':'/cadastro'}>{register?'Entrar':'Criar conta'}</Link></p></div><div className="auth-aside"><blockquote>“Um material parado pode ser exatamente o que falta para alguém continuar aprendendo.”</blockquote><div><span>♻️</span><p><b>Reutilize com propósito</b><br/>Reduza desperdícios e gere impacto local.</p></div></div></div> }
export const Login=()=> <AuthForm/>; export const Register=()=> <AuthForm register/>;

export function Donations() { const {user}=useAuth(); const [items,setItems]=useState([]),[error,setError]=useState(''); const load=()=>api(`/items?userId=${user.id}`).then(setItems).catch(e=>setError(e.message)); useEffect(load,[user.id]); const remove=async id=>{if(!confirm('Excluir esta doação?'))return;try{await api(`/items/${id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}}; return <div className="page"><PageHeading eyebrow="Sua contribuição" title="Minhas doações" text="Acompanhe e gerencie os materiais que você colocou em circulação." action={<Link className="button" to="/doacoes/nova">+ Nova doação</Link>}/><Notice error={error}/>{items.length?<div className="management-list">{items.map(i=><article key={i.id}><span className="mini-icon">{categoryIcons[i.category]}</span><div><small>{categoryNames[i.category]}</small><h3>{i.name}</h3><p>{conditionNames[i.condition]} · {i.availability==='AVAILABLE'?'Disponível':'Doado'}</p></div><button className="danger-link" onClick={()=>remove(i.id)}>Excluir</button></article>)}</div>:<Empty title="Sua primeira doação começa aqui" text="Cadastre um material em bom estado e ajude alguém a continuar aprendendo." action={<Link className="button" to="/doacoes/nova">Cadastrar material</Link>}/>}</div> }

export function NewDonation() { const navigate=useNavigate(); const [form,setForm]=useState({name:'',description:'',category:'NOTEBOOK',condition:'GOOD'}),[error,setError]=useState(''); const submit=async e=>{e.preventDefault();try{await api('/items',{method:'POST',body:JSON.stringify(form)});navigate('/doacoes')}catch(err){setError(err.message)}}; return <div className="page narrow"><Link className="back" to="/doacoes">← Voltar</Link><PageHeading eyebrow="Compartilhe oportunidades" title="Cadastrar uma doação" text="Descreva o material com clareza para ajudar quem está procurando."/><form className="card-form" onSubmit={submit}><label>Nome do material<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Mochila escolar azul"/></label><label>Descrição<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Conte sobre conservação, tamanho e detalhes importantes."/></label><div className="form-row"><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.entries(categoryNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label>Estado<select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value})}>{Object.entries(conditionNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label></div><Notice error={error}/><button className="button">Publicar doação</button></form></div> }

export function Orders() { const [tab,setTab]=useState('mine'),[orders,setOrders]=useState([]),[error,setError]=useState(''); const load=()=>api(`/orders/${tab}`).then(setOrders).catch(e=>setError(e.message)); useEffect(load,[tab]); const change=async(id,status)=>{try{await api(`/orders/${id}`,{method:'PATCH',body:JSON.stringify({status})});load()}catch(e){setError(e.message)}}; return <div className="page"><PageHeading eyebrow="Acompanhe cada conexão" title="Pedidos" text="Veja suas solicitações e os pedidos recebidos em suas doações."/><div className="tabs"><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>Minhas solicitações</button><button className={tab==='received'?'active':''} onClick={()=>setTab('received')}>Pedidos recebidos</button></div><Notice error={error}/>{orders.length?<div className="management-list">{orders.map(o=><article key={o.id}><span className="mini-icon">{categoryIcons[o.item.category]}</span><div><small>{statusNames[o.status]}</small><h3>{o.item.name}</h3><p>{tab==='received'?`Solicitado por ${o.user.name}`:`Doação de ${o.item.user?.name||'membro da comunidade'}`}</p></div>{tab==='received'&&o.status==='PENDING'&&<div className="row-actions"><button onClick={()=>change(o.id,'APPROVED')}>Aprovar</button><button onClick={()=>change(o.id,'CANCELED')}>Recusar</button></div>}{tab==='received'&&o.status==='APPROVED'&&<button onClick={()=>change(o.id,'COMPLETED')}>Concluir</button>}</article>)}</div>:<Empty title="Nenhum pedido por aqui" text="Quando houver uma solicitação, ela aparecerá nesta página."/>}</div> }

export function Profile() { const {user}=useAuth(); return <div className="page narrow"><PageHeading eyebrow="Sua conta" title="Perfil" text="Informações usadas para participar da rede Passe Adiante."/><div className="profile-card"><div className="profile-avatar">{user.name?.[0]}</div><h2>{user.name}</h2><span className="role">{user.type==='ADMIN'?'Administrador':user.type==='DONOR'?'Doador':'Participante'}</span><dl><div><dt>E-mail</dt><dd>{user.email}</dd></div><div><dt>Telefone</dt><dd>{user.phones?.join(', ')||'Não informado'}</dd></div><div><dt>Localização</dt><dd>{user.address||'Não informada'}</dd></div></dl></div></div> }

export function Admin() { const [tab,setTab]=useState('users'),[data,setData]=useState([]),[error,setError]=useState(''); const load=()=>api(adminPaths[tab]).then(setData).catch(e=>setError(e.message)); useEffect(load,[tab]); const stats=useMemo(()=>({users:tab==='users'?data.length:'—',items:tab==='items'?data.length:'—',orders:tab==='orders'?data.length:'—'}),[tab,data]); return <div className="page admin-page"><PageHeading eyebrow="Visão geral" title="Painel administrativo" text="Acompanhe a comunidade e mantenha a plataforma organizada."/><div className="admin-stats"><article><span>👥</span><div><b>{stats.users}</b><small>usuários carregados</small></div></article><article><span>🎒</span><div><b>{stats.items}</b><small>itens carregados</small></div></article><article><span>↗</span><div><b>{stats.orders}</b><small>pedidos carregados</small></div></article></div><div className="tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Usuários</button><button className={tab==='items'?'active':''} onClick={()=>setTab('items')}>Itens</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pedidos</button></div><Notice error={error}/><div className="table-wrap"><table><thead><tr><th>Registro</th><th>Detalhes</th><th>Status / perfil</th></tr></thead><tbody>{data.map(row=><tr key={row.id}><td><b>{row.name||row.item?.name||row.id.slice(0,8)}</b></td><td>{row.email||row.description||row.user?.email||'—'}</td><td><span className="status-pill">{statusNames[row.status]||conditionNames[row.condition]||row.type}</span></td></tr>)}</tbody></table></div></div> }

export function About() { return <div className="page narrow prose"><PageHeading eyebrow="Nossa missão" title="Materiais parados, futuros em movimento" text="O Passe Adiante nasceu para aproximar solidariedade, educação e sustentabilidade."/><h2>Por que existimos</h2><p>Muitas famílias guardam cadernos, mochilas e livros em bom estado, enquanto estudantes próximos enfrentam dificuldades para adquirir esses mesmos recursos. A plataforma cria uma ponte simples e gratuita entre essas realidades.</p><h2>Quem pode participar</h2><p>Estudantes, famílias, escolas, ONGs, instituições sociais e pequenos comércios podem doar, solicitar ou apoiar campanhas locais. Cada item reaproveitado reduz desperdício e amplia oportunidades educacionais.</p><Link className="button" to="/cadastro">Fazer parte da rede</Link></div> }
export const Forbidden=()=> <div className="error-page"><b>403</b><h1>Acesso restrito</h1><p>Seu perfil não possui permissão para acessar esta área.</p><Link className="button" to="/">Voltar ao início</Link></div>
export const NotFound=()=> <div className="error-page"><b>404</b><h1>Página não encontrada</h1><p>Este caminho não existe ou foi movido.</p><Link className="button" to="/">Voltar ao início</Link></div>
